codebender_library_status_check:
    pattern:  /status
    defaults: { _controller: CodebenderLibraryBundle:Default:status }

codebender_unit_test:
    pattern:  /{authorizationKey}/test
    defaults: { _controller: CodebenderLibraryBundle:Test:test }

codebender_library_view_library:
    pattern:  /{authorizationKey}/view
    defaults: { _controller: CodebenderLibraryBundle:Views:viewLibrary }

codebender_library_get_library_git_meta:
    pattern: /{authorizationKey}/getlibgitmeta
    defaults: {_controller:CodebenderLibraryBundle:Default:getLibraryGitMeta}
    methods:  [POST]

codebender_library_download:
    pattern: /{authorizationKey}/download/{library}
    defaults: { _controller: CodebenderLibraryBundle:Views:download }

codebender_library_new_external:
    pattern: /{authorizationKey}/new
    defaults: {_controller:CodebenderLibraryBundle:Views:newLibrary}
    methods:  [GET, POST]

codebender_library_check_github_updates:
    pattern: /{authorizationKey}/gitUpdates
    defaults: {_controller:CodebenderLibraryBundle:Views:gitUpdates}

codebender_library_search:
    pattern: /{authorizationKey}/search
    defaults: { _controller: CodebenderLibraryBundle:Views:search }

codebender_library_status_change:
    pattern: /{authorizationKey}/toggleStatus/{library}
    defaults: {_controller:CodebenderLibraryBundle:Views:changeLibraryStatus}
    methods:  [POST]

codebender_library_get_keywords:
    pattern:  /{authorizationKey}/{version}/getKeywords
    defaults: { _controller: CodebenderLibraryBundle:Default:getKeywords}

codebender_api_handler:
    pattern:  /{authorizationKey}/{version}
    defaults: { _controller: CodebenderLibraryBundle:Default:apiHandler }
    methods:  [POST]
