parameters:
#    codebender_library.example.class: Codebender\LibraryBundle\Example
    codebender_library.handler.class: Codebender\LibraryBundle\Handler\DefaultHandler
    codebender_library.apiHandler.class: Codebender\LibraryBundle\Handler\ApiHandler
    codebender_library.apiCommandHandler.class: Codebender\LibraryBundle\Handler\ApiCommandHandler

# Publicly accessible APIs
    codebender_api.status.class: Codebender\LibraryBundle\Handler\ApiCommand\StatusCommand
    codebender_api.invalidApi.class: Codebender\LibraryBundle\Handler\ApiCommand\InvalidApiCommand
    codebender_api.getExamples.class: Codebender\LibraryBundle\Handler\ApiCommand\GetExamplesCommand
    codebender_api.getVersions.class: Codebender\LibraryBundle\Handler\ApiCommand\GetVersionsCommand
    codebender_api.getKeywords.class: Codebender\LibraryBundle\Handler\ApiCommand\GetKeywordsCommand

services:
#    codebender_library.example:
#        class: %codebender_library.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    codebender_library.handler:
        class:  %codebender_library.handler.class%
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            containerInterface: "@service_container"

    codebender_library.apiHandler:
            class:  %codebender_library.apiHandler.class%
            arguments:
                entityManager: "@doctrine.orm.entity_manager"
                containerInterface: "@service_container"

    codebender_library.apiCommandHandler:
            class:  %codebender_library.apiCommandHandler.class%
            arguments:
                entityManager: "@doctrine.orm.entity_manager"
                containerInterface: "@service_container"

# Publicly accessible services
    codebender_api.status:
            class:  %codebender_api.status.class%
            arguments:
                entityManager: "@doctrine.orm.entity_manager"
                containerInterface: "@service_container"

    codebender_api.invalidApi:
            class:  %codebender_api.invalidApi.class%
            arguments:
                entityManager: "@doctrine.orm.entity_manager"
                containerInterface: "@service_container"

    codebender_api.getExamples:
            class:  %codebender_api.getExamples.class%
            arguments:
                entityManager: "@doctrine.orm.entity_manager"
                containerInterface: "@service_container"

    codebender_api.getVersions:
            class:  %codebender_api.getVersions.class%
            arguments:
                entityManager: "@doctrine.orm.entity_manager"
                containerInterface: "@service_container"

    codebender_api.getKeywords:
            class:  %codebender_api.getKeywords.class%
            arguments:
                entityManager: "@doctrine.orm.entity_manager"
                containerInterface: "@service_container"
